### ISSUE TITLE
High severity vulnerability in `node-forge` so `firebase-admin` update is required

### ISSUE THREAD

**Issue by dominikfoldi** [Jblew/firebase-functions-rate-limiter#15]
There is a new advisory about `node-forge` which is an indirect dependency of `firebase-admin`, see: https://www.npmjs.com/advisories/1561 

The `firebase-admin` dependency should be updated to a version which doesn't contain the vulnerability.

**Comment by Jblew** [comment]
Thanks a lot for commenting and for bringing my attention to this. I've just updated all dependencies in version **3.8.3**. 
Please test if the version works for you: `npm i firebase-functions-rate-limiter@3.8.3` :)

**Comment by dominikfoldi** [comment]
Thank you @Jblew! Just tested it and it is working great!
